export const Users = [
  {
    id: 1,
    profilePicture: "assets/person/1.jpeg",
    username: "Mahdi Zaman",
  },
  {
    id: 2,
    profilePicture: "assets/person/2.jpeg",
    username: "Mahdi Zaman",
  },
  {
    id: 3,
    profilePicture: "assets/person/3.jpeg",
    username: "Mahdi Zaman",
  },
  {
    id: 4,
    profilePicture: "assets/person/4.jpeg",
    username: "Mahdi Zaman",
  },
  {
    id: 5,
    profilePicture: "assets/person/5.jpeg",
    username: "Mahdi Zaman",
  },
  {
    id: 6,
    profilePicture: "assets/person/6.jpeg",
    username: "Mahdi Zaman",
  },
  {
    id: 7,
    profilePicture: "assets/person/7.jpeg",
    username: "Mahdi Zaman",
  },
  {
    id: 8,
    profilePicture: "assets/person/8.jpeg",
    username: "Mahdi Zaman",
  },
  {
    id: 9,
    profilePicture: "assets/person/9.jpeg",
    username: "Mahdi Zaman",
  },
  {
    id: 10,
    profilePicture: "assets/person/10.jpeg",
    username: "Mahdi Zaman",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love for all ,hatred for none",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "Love for all ,hatred for none",
    photo: "assets/post/2.jpeg",
    date: "5 mins ago",
    userId: 2,
    like: 3,
    comment: 92,
  },
  {
    id: 3,
    desc: "Love for all ,hatred for none",
    photo: "assets/post/3.jpeg",
    date: "35 mins ago",
    userId: 3,
    like: 23,
    comment: 39,
  },
  {
    id: 4,
    desc: "Love for all ,hatred for none",
    photo: "assets/post/4.jpeg",
    date: "45 mins ago",
    userId: 4,
    like: 43,
    comment: 4,
  },
  {
    id: 5,
    desc: "Love for all ,hatred for none",
    photo: "assets/post/5.jpeg",
    date: "5 mins ago",
    userId: 5,
    like: 32,
    comment: 15,
  },
  {
    id: 6,
    desc: "Love for all ,hatred for none",
    photo: "assets/post/6.jpeg",
    date: "16 mins ago",
    userId: 6,
    like: 16,
    comment: 26,
  },
  {
    id: 7,
    desc: "Love for all ,hatred for none",
    photo: "assets/post/7.jpeg",
    date: "57 mins ago",
    userId: 7,
    like: 72,
    comment: 7,
  },
  {
    id: 8,
    desc: "Love for all ,hatred for none",
    photo: "assets/post/8.jpeg",
    date: "8 mins ago",
    userId: 8,
    like: 58,
    comment: 48,
  },
  {
    id: 9,
    desc: "Love for all ,hatred for none",
    photo: "assets/post/9.jpeg",
    date: "59 mins ago",
    userId: 9,
    like: 32,
    comment: 9,
  },
  {
    id: 10,
    desc: "Love for all ,hatred for none",
    photo: "assets/post/10.jpeg",
    date: "50 mins ago",
    userId: 10,
    like: 32,
    comment: 9,
  },
];
